# Generated by Django 4.0.3 on 2022-04-05 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reservation_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamedate', models.DateField()),
                ('gametime', models.TimeField()),
                ('max_num_of_players', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('list_of_players', models.ManyToManyField(blank=True, default=None, null=True, related_name='players', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reservation_App.sportpitches')),
            ],
        ),
    ]
