# Generated by Django 4.0.3 on 2022-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_App', '0002_cities_sportmatches_listofplayers_sportpitches_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofplayers',
            name='player',
        ),
        migrations.AddField(
            model_name='listofplayers',
            name='playerName',
            field=models.CharField(default='Admin', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
