# Generated by Django 4.0.3 on 2022-04-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_App', '0003_cities_sportpitches_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportpitches',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Reservation_App.cities'),
        ),
    ]
