# Generated by Django 4.0.3 on 2022-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_App', '0003_remove_listofplayers_player_listofplayers_playername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofplayers',
            name='playerName',
            field=models.CharField(max_length=30),
        ),
    ]
