# Generated by Django 4.0.3 on 2022-04-16 12:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_App', '0004_alter_listofplayers_playername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofplayers',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation_App.sportmatches'),
        ),
        migrations.AlterField(
            model_name='sportmatches',
            name='gamedate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.CreateModel(
            name='PitchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Hala'), (1, 'Na świeżym powietrzu'), (2, 'Pod balonem'), (3, 'Trawiaste'), (4, 'Sztuczna trawa'), (5, 'Tartan'), (6, 'Z szatnią'), (7, 'Brak szatni')], max_length=1)),
                ('pitches', models.ManyToManyField(to='Reservation_App.sportpitches')),
            ],
        ),
    ]
