# Generated by Django 4.0.3 on 2022-04-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_App', '0006_alter_pitchtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchtype',
            name='pitches',
        ),
        migrations.AddField(
            model_name='sportpitches',
            name='pitches',
            field=models.ManyToManyField(to='Reservation_App.pitchtype'),
        ),
    ]
