# Generated by Django 4.0.3 on 2022-04-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_App', '0007_remove_pitchtype_pitches_sportpitches_pitches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportpitches',
            old_name='pitches',
            new_name='type',
        ),
    ]
