# Generated by Django 4.0.3 on 2022-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_App', '0008_rename_pitches_sportpitches_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportpitches',
            name='type',
        ),
        migrations.AddField(
            model_name='sportpitches',
            name='pitches',
            field=models.ManyToManyField(blank=True, to='Reservation_App.pitchtype'),
        ),
    ]
